# Generated by Django 4.0.4 on 2022-08-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_remove_company_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição da Produto')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, max_length=255, null=True, verbose_name='valor')),
                ('category', models.CharField(blank=True, choices=[('', '----------------'), ('ENERGY', 'Conta de Energia'), ('WATER', 'Conta de Água'), ('GAS', 'Conta de Gás'), ('ADMINISTRATION_FEE', 'Taxa de Administração'), ('CLEANING_FEE', 'Taxa de Limpeza'), ('RESERVE_FUND', 'Fundo de Reserva'), ('OTHER', 'Outro')], max_length=50, null=True, verbose_name='Categoria')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
    ]
