# Generated by Django 4.0.4 on 2022-08-30 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, max_length=255, null=True, verbose_name='valor')),
                ('category', models.CharField(blank=True, choices=[('', '----------------'), ('ENERGY', 'Conta de Energia'), ('WATER', 'Conta de Água'), ('GAS', 'Conta de Gás'), ('ADMINISTRATION_FEE', 'Taxa de Administração'), ('CLEANING_FEE', 'Taxa de Limpeza'), ('RESERVE_FUND', 'Fundo de Reserva'), ('OTHER', 'Outro')], max_length=50, null=True, verbose_name='Tipo de conta')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Cliente')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'Valor de Custo',
                'verbose_name_plural': 'Valores de Custo',
                'db_table': 'cost_vaqlue',
            },
        ),
    ]
