# Generated by Django 4.0.4 on 2022-08-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
        ('sales_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salles',
            new_name='Sales',
        ),
    ]
