# Generated by Django 4.0.4 on 2022-07-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
    ]
