# Generated by Django 4.0.4 on 2022-07-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='picture',
        ),
    ]
